version: 3
automerge: true
autoplan: false
projects:
  - name: prod-aws
    dir: terraform/environments/prod-aws
    workspace: default
    autoplan:
      enabled: true
      when_modified:
        - "../../modules/**"
        - "*.tf"
    workflow: terraform-prod
  - name: prod-gcp
    dir: terraform/environments/prod-gcp
    workspace: default
    autoplan:
      enabled: true
      when_modified:
        - "../../modules/**"
        - "*.tf"
    workflow: terraform-prod
workflows:
  terraform-prod:
    plan:
      steps:
        - env:
            name: TF_VAR_image_tag
            command: echo \"${ATLANTIS_PULL_NUM}-sha${ATLANTIS_PULL_SHA:0:7}\"
        - init:
            extra_args: ["-backend-config=../backend.tfvars"]
        - plan:
            extra_args: ["-input=false"]
    apply:
      steps:
        - apply
