apiVersion: apps/v1
kind: Deployment
metadata:
  name: arlo-demo-app
  namespace: api
  labels:
    app.kubernetes.io/name: arlo-demo-app
    app.kubernetes.io/part-of: arlo-resilience
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: arlo-demo-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: arlo-demo-app
        app.kubernetes.io/part-of: arlo-resilience
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: arlo-demo-service
      securityContext:
        runAsNonRoot: true
        fsGroup: 2000
      containers:
        - name: web
          image: ghcr.io/arlo-resilience/arlo-demo-app:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: CLUSTER_NAME
              value: "multi-cloud"
            - name: CLUSTER_REGION
              value: "global"
            - name: PRIMARY_PROVIDER
              value: "aws"
            - name: FAILOVER_PROVIDER
              value: "gcp"
          envFrom:
            - secretRef:
                name: arlo-demo-secrets
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - arlo-demo-app
                topologyKey: kubernetes.io/hostname
