apiVersion: v1
kind: Namespace
metadata:
  name: api
  labels:
    app.kubernetes.io/name: arlo-demo
    app.kubernetes.io/part-of: arlo-resilience
---
apiVersion: v1
kind: Namespace
metadata:
  name: db
  labels:
    app.kubernetes.io/part-of: arlo-resilience
    monitoring: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: arlo-resilience
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: arlo-resilience
