global:
  scrape_interval: 30s
  scrape_timeout: 15s
  evaluation_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager.monitoring.svc:9093

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: eks-kubernetes
    honor_labels: true
    kubernetes_sd_configs:
      - role: pod
        api_server: https://kubernetes.default.svc
        namespaces:
          names:
            - monitoring
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: keep
        regex: monitoring
      - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
        action: keep
        regex: prometheus-node-exporter|kube-state-metrics|arlo-demo-app
  - job_name: gke-federation
    scrape_interval: 60s
    metrics_path: /federate
    honor_labels: true
    params:
      'match[]':
        - '{job="argo-app"}'
        - '{job="kube-state-metrics"}'
    scheme: https
    static_configs:
      - targets:
          - gke-prometheus.arlo-resilience.com
    basic_auth:
      username: federated
      password: ${PROMETHEUS_GKE_PASSWORD}
  - job_name: cloudwatch-exporter
    static_configs:
      - targets:
          - cloudwatch-exporter.monitoring.svc:9106
    metrics_path: /metrics
  - job_name: google-cloud-monitoring
    static_configs:
      - targets:
          - stackdriver-exporter.monitoring.svc:9255
