apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake-aws-secrets
spec:
  provider:
    fake:
      data:
        - key: arlo/prod/api
          value: |
            {
              "apiKey": "local-key",
              "dynamoEndpoint": "http://dynamodb-local:8000"
            }
