apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - clustersecretstore.yaml
  - externalsecret.yaml
  - ingress.yaml

patchesStrategicMerge:
  - deployment-patch.yaml
  - serviceaccount-patch.yaml
